# netlify.toml

[build]
  # Configura el directorio de publicación
  publish = "dist"

[[headers]]
for = "/*"
  [headers.values]
  # Desactiva la caché para todos los archivos
  Cache-Control = "no-cache"

[[headers]]
for = "/productos"
  [headers.values]
  # Desactiva la caché específicamente para el endpoint de productos
  Cache-Control = "no-cache"

# Configuración adicional si es necesario
# Puedes añadir otros encabezados o configuraciones aquí
